### ISSUE TITLE
this repo is excluded from hacktoberfest 2022 website

### ISSUE THREAD

**Issue by rajdeepdas2000** [Rjndrkha/HacktoberFest_2022#546]
![image](https://user-images.githubusercontent.com/53941109/193893770-58f7476f-3fa3-4ec3-a40e-1010efb9e176.png)

**Comment by ItzLevvie** [comment]
There is a commitment — which is a **_compulsary_** requirement — for contributors & maintainers to follow a set of guidelines which is listed [here](https://hacktoberfest.com/participation/).

This repository does not fall into the guidelines that were initially set by DigitalOcean. More specifically, this statement: "**_PR/MRs should be useful to maintainers. Repos that encourage simplistic PR/MRs (like adding a name or profile to a list or arbitrarily curating content) will be excluded from Hacktoberfest._**"

^ If you would like me to be even more specific - it's these 3 words: **_arbitrarily curating content_**

This repository was created for the sole purpose of allowing people to contribute pull requests (PRs) with no real purpose other than to be in the "minimum 4 pull requests (PRs)" window to be eligible for a T-Shirt from DigitalOcean.

This 1 week (7 days) of waiting time was implemented so that DigitalOcean can review more than 500K pull requests to ensure that each pull request (PR) meets the guidelines set. Lots of human moderators were chosen by DigitalOcean to take care of this.

If a particular repository was never reported to DigitalOcean where the sole purpose was to defeat the system - it's always — 50% to 75% — possible for your pull requests (PRs) to be flagged and have it **_not_** counted towards your contributions for Hacktoberfest 2022.

As always, humans are humans - and not robots. This means that it's sometimes possible for these pull requests (PRs) to slip through DigitalOcean's reviews and have your pull requests (PRs) counted towards your contributions for Hacktoberfest 2022.

Please be aware that if you made multiple repositories which were all excluded - it's better to be **_safe_** than sorry to say that it's always possible for DigitalOcean to blacklist your GitHub / GitLab account where any pull request (PR) made by other contributors to your repositories will not have their contributions counted towards Hacktoberfest 2022.

DigitalOcean is always looking to implement more safeguarding measures to prevent unfair unadvantage towards other people and every October in each year, those rules tend to expand.
